import "babel-polyfill";
import 'classnames/bind';
import 'history';
import 'immutable';
import 'lodash';
import 'pluralize';
import 'prop-types';
import 'query-string';
import 'react';
import 'react-dom';
import 'react-immutable-proptypes';
import 'react-redux';
import 'react-router';
import 'react-router-dom';
import 'react-router-redux';
import 'react-tap-event-plugin';
import 'react-transition-group';
import 'redux';
import 'redux-immutable';
import 'reselect';
import 'rxjs';
import 'string-format';
import 'custom-event-polyfill';
import { polyfill as smoothScrollPolyfill } from 'smoothscroll-polyfill';

smoothScrollPolyfill();
